New_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('home.urls')),
    path('products/', include('product.urls')),
    path('shopping/', include('order.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('',  views.Home, name='home')
]

order/urls.py
from django.urls import path
from . import views
app_name = 'order'
urlpatterns = [
    path('order/', views.OrderingView.as_view(), name='order'),
    path('add/<int:pk>', views.OrderADdDetail.as_view(), name='add_order'),
    path('delete/<str:id>', views.OrderDeleteView.as_view(), name='delete_order'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='detail_order'),
    path('create/order', views.OrderCreationView.as_view(), name='create_order'),
    path('applydiscount/<int:pk>', views.ApplyDiscountView.as_view(), name='apply_discount'),

]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'
urlpatterns = [
    path('detail/<int:pk>', views.ProductDetailView.as_view(), name='product_detail'),
    path('navbar', views.NavbarePartialView.as_view(), name='navbar'),
    path('sample', views.SampleCategoryView.as_view(), name='sample_category'),
    path('list', views.ProductListView.as_view(), name='product_list'),
]

product/models.py
import datetime
from datetime import timezone

from django.db import models


class Size(models.Model):
    title = models.CharField(max_length=10)


    def __str__(self):
        return self.title
class Color(models.Model):
    title = models.CharField(max_length=10)


    def __str__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(max_length=35)
    description = models.TextField()
    price = models.IntegerField(default=100000)
    discount = models.SmallIntegerField(blank=True, null=True, default=0)
    image = models.FileField(upload_to='products')
    size = models.ManyToManyField(Size, blank=True, null=True, related_name='products')
    color = models.ManyToManyField(Color, related_name='colors',)
    created = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return self.title


class Information(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.CASCADE, related_name='information')
    text = models.TextField()


    def __str__(self):
        return self.text



class Category(models.Model):
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='subs')
    title = models.CharField(max_length=35)
    slug = models.SlugField()

    def __str__(self):
        return self.title

product/views.py
from django.shortcuts import render
from django.views.generic import DetailView, TemplateView, ListView
from django.core.paginator import Paginator
from product.models import Product, Category, Size, Color


class ProductDetailView(DetailView):
    template_name = 'product/detail.html'
    model = Product


class NavbarePartialView(TemplateView):
    template_name = 'includes/navbar.html'

    def get_context_data(self, **kwargs):
        contex = super(NavbarePartialView, self).get_context_data()  # super for get_contex_data
        contex['categories'] = Category.objects.all()

        return contex


class SampleCategoryView(TemplateView):
    template_name = 'category.html'

    def get_context_data(self, **kwargs):
        contex = super(SampleCategoryView, self).get_context_data()
        contex['categories'] = Category.objects.all()

        return contex


class ProductListView(ListView):
    template_name = 'product/shop.html'
    queryset = Product.objects.all()
    paginate_by = 6
    model = Product
    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data()
        context['size'] = Size.objects.all()
        context['color'] = Color.objects.all()

        selected_colors = self.request.GET.getlist('color')
        selected_sizes = self.request.GET.getlist('size')
        min_price = self.request.GET.get('min-price')
        max_price = self.request.GET.get('max-price')

        final_queryset = Product.objects.all()
        queryset = Product.objects.all()


        if selected_colors:
            queryset = Product.objects.filter(color__title__in=selected_colors).distinct()
        if selected_sizes:
            queryset = Product.objects.filter(size__title__in=selected_sizes).distinct()
        if min_price and max_price:
            queryset = Product.objects.filter(price__lte=max_price, price__gte=min_price)

        if selected_colors or selected_sizes or (min_price is not None and max_price is not None):
            final_queryset = Product.objects.none()

            if selected_colors:
                final_queryset = queryset.filter(color__title__in=selected_colors)

            if selected_sizes:
                final_queryset = final_queryset.filter(size__title__in=selected_sizes)

            if min_price is not None and max_price is not None:
                final_queryset = final_queryset.filter(price__range=(min_price, max_price))
        context['object_list'] = final_queryset.distinct()


        # print(selected_colors, selected_sizes, min_price, max_price)

        paginator = Paginator(queryset, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context['object_list'] = page_obj
        context['selected_colors'] = selected_colors
        context['min_price'] = min_price
        context['max_price'] = max_price
        context['selected_sizes'] = selected_sizes
        context['page_obj'] = page_obj

        return context

product/templates/product/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'home:home' %}">Home</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'product:product_list' %}">Shop</a>
                    <span class="breadcrumb-item active">Shop Detail</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Detail Start -->
    <div class="container-fluid pb-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 mb-30">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner bg-light">


                        <div class="carousel-item active">
                            <img class="w-100 h-100" src="{{ product.image.url }}" alt="Image">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#product-carousel" data-slide="prev">
                        <i class="fa fa-2x fa-angle-left text-dark"></i>
                    </a>
                    <a class="carousel-control-next" href="#product-carousel" data-slide="next">
                        <i class="fa fa-2x fa-angle-right text-dark"></i>
                    </a>
                </div>
            </div>

            <div class="col-lg-7 h-auto mb-30">
                <div class="h-100 bg-light p-30">
                    <h3>{{ product.title }}</h3>
                    <h3 class="font-weight-semi-bold mb-4">{{ product.price }}</h3>
                    <p class="mb-4">{{ product.description|truncatewords:10 }}</p>
                    <div class="d-flex mb-3">
                        {% if product.size.all %}
                            <strong class="text-dark mr-3">Sizes:</strong>
                        {% endif %}
                        <form action="{% url 'order:add_order' product.id %}" method="post">
                            {% csrf_token %}
                            {% for size in product.size.all %}
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" class="custom-control-input" value="{{ size.title }}"
                                           id="{{ size.title }}" name="size">
                                    <label class="custom-control-label" for="{{ size.title }}">{{ size.title }}</label>
                                </div>
                            {% endfor %}

                            <div class="d-flex mb-4">
                                {% if product.color.all %}
                                    <strong class="text-dark mr-3">Colors:</strong>
                                {% endif %}

                                {% for color in product.color.all %}
                                    <div class="custom-control custom-radio custom-control-inline">
                                        <input type="radio" class="custom-control-input" value="{{ color.title }}"
                                               id="{{ color.title }}" name="color">
                                        <label class="custom-control-label"
                                               for="{{ color.title }}">{{ color.title }}</label>
                                    </div>
                                {% endfor %}

                            </div>
                            <div class="d-flex align-items-center mb-4 pt-2">
                                <div class="input-group quantity mr-3" style="width: 130px;">
                                    <div class="input-group-btn">
                                        <button type="button" class="btn btn-primary btn-minus">
                                            <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="text" name="Quantity" class="form-control bg-secondary border-0 text-center" value="1">
                                    <div class="input-group-btn">
                                        <button type="button" class="btn btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                                <button class="btn btn-primary px-3"><i class="fa fa-shopping-cart mr-1"></i> Add To
                                    Cart
                                </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row px-xl-5">
            <div class="col">
                <div class="bg-light p-30">
                    <div class="nav nav-tabs mb-4">
                        <a class="nav-item nav-link text-dark active" data-toggle="tab"
                           href="#tab-pane-1">Description</a>
                        <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-2">Information</a>
                        <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-3">Reviews (0)</a>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab-pane-1">
                            <h4 class="mb-3">Product Description</h4>
                            <p>{{ product.description|linebreaksbr }}</p>
                        </div>
                        <div class="tab-pane fade" id="tab-pane-2">
                            <h4 class="mb-3">Additional Information</h4>
                            <p>{{ product.infoText|linebreaksbr }}</p>
                            <div class="row">
                                <div class="col-md-6">
                                    <ul class="list-group list-group-flush">
                                        {% for info in product.information.all %}
                                            {% if forloop.counter|divisibleby:2 %}
                                                <li class="list-group-item px-0">
                                                    {{ info }}
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                </div>
                                <div class="col-md-6">
                                    <ul class="list-group list-group-flush">
                                        {% for info in product.information.all %}
                                            {% if forloop.counter0|divisibleby:2 %}
                                                <li class="list-group-item px-0">
                                                    {{ info }}
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="tab-pane-3">
                        <div class="row">
                            <div class="col-md-6">
                                <h4 class="mb-4">1 review for "Product Name"</h4>
                                <div class="media mb-4">
                                    <img src="{% static 'img/user.jpg' %}" alt="Image" class="img-fluid mr-3 mt-1"
                                         style="width: 45px;">
                                    <div class="media-body">
                                        <h6>John Doe<small> - <i>01 Jan 2045</i></small></h6>
                                        <p>Diam amet duo labore stet elitr ea clita ipsum, tempor labore accusam
                                            ipsum et no at. Kasd diam tempor rebum magna dolores sed sed eirmod
                                            ipsum.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <h4 class="mb-4">Leave a review</h4>
                                <small>Your email address will not be published. Required fields are marked
                                    *</small>
                                <form>
                                    <div class="form-group">
                                        <label for="message">Your Review *</label>
                                        <textarea id="message" cols="30" rows="5" class="form-control"></textarea>
                                    </div>
                                    <div class="form-group">
                                        <label for="name">Your Name *</label>
                                        <input type="text" class="form-control" id="name">
                                    </div>
                                    <div class="form-group">
                                        <label for="email">Your Email *</label>
                                        <input type="email" class="form-control" id="email">
                                    </div>
                                    <div class="form-group mb-0">
                                        <input type="submit" value="Leave Your Review" class="btn btn-primary px-3">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- Shop Detail End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

    <!-- Products End -->
{% endblock content %}

product/templates/product/shop.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row px-xl-5">
        <!-- Shop Sidebar Start -->
        <div class="col-lg-3 col-md-4">
            <!-- Price Start -->
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by price</span>
            </h5>
            <div class="bg-light p-4 mb-30">
                <form method="get">
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <label for="min-price">min</label>
                        <input type="number" id="min-price" {% if min_price %}value="{{ min_price }}" {% endif %}
                               name="min-price">
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <label for="max-price">max</label>
                        <input type="number" id="max-price" {% if max_price %}value="{{ max_price }}" {% endif %}
                               name="max-price">
                    </div>
            </div>
            <!-- Price End -->
            <!-- Color Start -->
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by color</span>
            </h5>
            <div class="bg-light p-4 mb-30">
                {% for x in color %}
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="{{ x.title }}" name="color"
                               value="{{ x.title }}" {% if x.title in selected_colors %}checked{% endif %}>
                        <label class="custom-control-label" for="{{ x.title }}">{{ x.title }}</label>
                    </div>
                {% endfor %}

            </div>
            <!-- Color End -->

            <!-- Size Start -->
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by size</span>
            </h5>
            <div class="bg-light p-4 mb-30">
                {% for x in size %}
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="{{ x.title }}" name="size"
                               value="{{ x.title }}" {% if x.title in selected_sizes %}checked{% endif %}>
                        <label class="custom-control-label" for="{{ x.title }}">{{ x.title }}</label>
                    </div>
                {% endfor %}
                <input class="button" type="submit">
                </form>
            </div>
            <!-- Size End -->
        </div>
        <!-- Shop Sidebar End -->
        <!-- Shop Product Start -->
        <div class="col-lg-9 col-md-8">
            <div class="row pb-3">
                <div class="col-12 pb-1">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <div>
                            <button class="btn btn-sm btn-light"><i class="fa fa-th-large"></i></button>
                            <button class="btn btn-sm btn-light ml-2"><i class="fa fa-bars"></i></button>
                        </div>
                        <div class="ml-2">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-light dropdown-toggle"
                                        data-toggle="dropdown">Sorting
                                </button>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="#">Latest</a>
                                    <a class="dropdown-item" href="#">Popularity</a>
                                    <a class="dropdown-item" href="#">Best Rating</a>
                                </div>
                            </div>
                            <div class="btn-group ml-2">
                                <button type="button" class="btn btn-sm btn-light dropdown-toggle"
                                        data-toggle="dropdown">Showing
                                </button>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="#">10</a>
                                    <a class="dropdown-item" href="#">20</a>
                                    <a class="dropdown-item" href="#">30</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% for object in object_list %}
                    <div class="col-lg-4 col-md-6 col-sm-6 pb-1">
                        <div class="product-item bg-light mb-4">
                            <div class="product-img position-relative overflow-hidden">
                                <img class="img-fluid w-100" src="{{ object.image.url }}" alt="">
                                <div class="product-action">
                                    <a class="btn btn-outline-dark btn-square" href=""><i
                                            class="fa fa-shopping-cart"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i
                                            class="fa fa-sync-alt"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-search"></i></a>
                                </div>
                            </div>
                            <div class="text-center py-4">
                                <a class="h6 text-decoration-none text-truncate"
                                   href="{% url 'product:product_detail' object.id %}">{{ object.title }}</a>
                                <div class="d-flex align-items-center justify-content-center mt-2">
                                    <h5>${{ object.price }}</h5><h6 class="text-muted ml-2"></h6>
                                    {#                                    del>${{ object.price }}</del>#}
                                </div>

                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="col-12">
                    <nav>
                        {% if is_paginated %}
                            <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link"
                                       href="?page=1"><<</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link"
                                       href="?page={{ page_obj.previous_page_number }}"><</a>
                                </li>
                            {% endif %}
                            {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active">
                                    <a class="page-link"
                                       href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                                </li>
                            {% elif page_obj.number > i|add:"-2" and page_obj.number < i|add:"2" %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                </li>
                            {% endif %}
                            </li>
                        {% endfor %}
                        {#                                    {% if page_obj.has_next %}#}
                        {#                                        <li class="page-item">#}
                        {#                                            <a class="page-link"#}
                        {#                                               href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>#}
                        {#                                        </li>#}
                        {#                                    {% endif %}#}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">></a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">>></a>
                            </li>
                        {% endif %}
                        </ul>
                        {% endif %}
                    </nav>
                </div>
            </div>
        </div>
        <!-- Shop Product End -->
    </div>
</div>
{% endblock %}