New_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('home.urls')),
    path('products/', include('product.urls')),
    path('shopping/', include('order.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='user_login'),
    path('register/', views.UserRegister.as_view(), name='user_register'),
    path('check_OTP/', views.Check_User_OTP.as_view(), name='user_check_OTP_register'),
    path('logout_user/', views.user_Logout, name='logout'),
    path('add/address', views.AddAddressView.as_view(), name='add_address'),
]

home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('',  views.Home, name='home')
]

order/urls.py
from django.urls import path
from . import views
app_name = 'order'
urlpatterns = [
    path('order/', views.OrderingView.as_view(), name='order'),
    path('add/<int:pk>', views.OrderADdDetail.as_view(), name='add_order'),
    path('delete/<str:id>', views.OrderDeleteView.as_view(), name='delete_order'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='detail_order'),
    path('create/order', views.OrderCreationView.as_view(), name='create_order'),
    path('applydiscount/<int:pk>', views.ApplyDiscountView.as_view(), name='apply_discount'),

]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'
urlpatterns = [
    path('detail/<int:pk>', views.ProductDetailView.as_view(), name='product_detail'),
    path('navbar', views.NavbarePartialView.as_view(), name='navbar'),
    path('sample', views.SampleCategoryView.as_view(), name='sample_category'),
    path('list', views.ProductListView.as_view(), name='product_list'),
]

order/models.py
from django.db import models

from accounts.models import User
from product.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    creadted_at = models.DateTimeField(auto_now_add=True)
    is_paid = models.BooleanField(default=False)
    total_price = models.IntegerField(default=0)
    def __str__(self):
        return self.user.phone



class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    pruduct = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='items')
    size = models.CharField(max_length=12, null=True)
    color = models.CharField(max_length=12, null=True)
    quantity = models.SmallIntegerField()
    price = models.PositiveIntegerField()


    def __str__(self):
        return self.order.user.phone

class DiscountCode(models.Model):
    name = models.CharField(max_length=10, unique=True)
    discount = models.SmallIntegerField(default=0)
    quantity = models.SmallIntegerField(default=1)


    def __str__(self):
        return self.name

order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import DetailView

from order.cart_module import Cart
from order.models import Order, OrderItem, DiscountCode
from product.models import Product


class OrderingView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'order/ordering.html', {'cart': cart})


class OrderADdDetail(View):
    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)
        size, color, Quantity = request.POST.get('size'), request.POST.get('color'), request.POST.get('Quantity')
        print(size, color, Quantity)
        # we create the module for session cart in the cart_module.py
        cart = Cart(request)  # this class create a session with name cart

        cart.add(product, color, size, Quantity)
        return redirect('order:order')


class OrderDeleteView(View):
    def get(self, request, id):
        cart = Cart(request)
        cart.delete(id)
        return redirect('order:order')


class OrderDetailView(View):
    def get(self, request, pk):
        order = get_object_or_404(Order, id=pk)
        return render(request, 'order/order_detail.html', {"order": order})


class OrderCreationView(View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user, total_price=int(cart.total()))
        for item in cart:
            OrderItem.objects.create(order=order, pruduct=item['product'], size=item['size'], color=item['color'],
                                     quantity=item['quantity'], price=item['price'])

        cart.remove()
        return redirect('order:detail_order', order.id)


class ApplyDiscountView(View):
    def post(self, request, pk):
        order = get_object_or_404(Order, id=pk)
        code = request.POST.get('discount_code')
        discount_code = get_object_or_404(DiscountCode, name=code)
        if discount_code.quantity == 0:
            return redirect('order:detail_order')
        order.total_price -= order.total_price * discount_code.discount/100
        order.save()
        discount_code.quantity -= 1
        discount_code.save()
        return redirect('order:detail_order', order.id)

order/templates/order/order_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'home:home' %}">Home</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'product:product_list' %}">Shop</a>
                    <span class="breadcrumb-item active">Shopping Cart</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                    <tr>
                        <th>image</th>
                        <th>title</th>
                        <th>price</th>
                        <th>Quantity</th>
                        <th>color</th>
                        <th>size</th>
                        <th>Total</th>
                    </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for item in order.items.all %}
                        <tr>
                            <td class="align-middle"><img src="{{ item.pruduct.image.url }}" alt="image"
                                                          style="width: 50px;"></td>
                            <td class="align-middle">{{ item.pruduct.title }}</td>
                            <td class="align-middle">{{ item.price }}</td>
                            <td class="align-middle">{{ item.quantity }}</td>
                            <td class="align-middle">{{ item.color }}</td>
                            <td class="align-middle">{{ item.size }}</td>
                            <td class="align-middle">{{ item.total }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" method="post" action="{% url 'order:apply_discount' order.id %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="discount_code" class="form-control border-0 p-4" placeholder="Discount Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span>
                </h5>
                <div class="bg-light p-30 mb-5">
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>{{ order.total_price }}</h5>
                        </div>
                    {% if request.user.addreses.all %}
                        <a href="{% url 'order:create_order' %}"
                           class="btn btn-block btn-success font-weight-bold my-3 py-3">Pay
                        </a>
                        {% endif %}
                    </div>


                    {% if request.user.addreses.all %}
                    <select class="form-control" aria-label="Default select example">
                        {% for x in request.user.addreses.all %}
                            <option value="3">{{ x.address }}</option>
                        {% endfor %}
                    </select>
                        <a href="{% url 'accounts:add_address' %}?next={% url 'order:detail_order' order.id %}"
                       class="btn btn-block btn-dark font-weight-bold my-3 py-3">add another address</a>
                    {% else %}
                    <a href="{% url 'accounts:add_address' %}?next={% url 'order:detail_order' order.id %}"
                       class="btn btn-block btn-primary font-weight-bold my-3 py-3">you don`t have any address, add
                        one</a>
                {% endif %}
                </div>

            </div>
        </div>
    </div>
    <!-- Cart End -->

{% endblock %}

order/templates/order/ordering.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'home:home' %}">Home</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'product:product_list' %}">Shop</a>
                    <span class="breadcrumb-item active">Shopping Cart</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                    <tr>
                        <th>image</th>
                        <th>title</th>
                        <th>price</th>
                        <th>Quantity</th>
                        <th>color</th>
                        <th>size</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for item in cart %}
                        <tr>
                            <td class="align-middle"><img src="{{ item.product.image.url }}" alt="image" style="width: 50px;"></td>
                            <td class="align-middle">{{ item.product.title }}</td>
                            <td class="align-middle">{{ item.price }}</td>
                            <td class="align-middle">{{ item.quantity }}</td>
                            <td class="align-middle">{{ item.color }}</td>
                            <td class="align-middle">{{ item.size }}</td>
                            <td class="align-middle">{{ item.total }}</td>
                            <td class="align-middle">
                                <a href="{% url 'order:delete_order' item.unique_id  %}" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" action="">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span>
                </h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>$150</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            <h6 class="font-weight-medium">$10</h6>
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>{{ cart.total }}</h5>
                        </div>
                        {% if request.user.is_authenticated %}
                        	<a href="{% url 'order:create_order' %}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout
                        </a>
                            {% else %}
                            <a href="{% url 'accounts:user_login' %}?next={% url 'order:order'  %}" class="btn btn-block btn-danger font-weight-bold my-3 py-3">login first
                        </a>
                        {% endif %} 

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->

{% endblock %}